version: "3.8"

services:
  server:
    build:
      context: ./server
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=4000
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:3000
      - DB_PATH=/app/data/chore-chart.sqlite
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: ./ui
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  node_modules:
